version: '3'
services:
    react:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
         - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c "npm start"
        ports:
         - "3000:3000"
        stdin_open: true